{{- $fullName := printf "%s-%s" (include "climbsheet.fullname" .) "cronjob" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
spec:
  schedule: "0 13 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: {{ $fullName }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: private-registry
          containers:
            - name: climbsheet
              imagePullPolicy: Always
              image: {{ .Values.image }}
              volumeMounts:
                - mountPath: "/data"
                  name: climbsheet-volume
              env:
                - name: CONFIG_PATH
                  value: "/data/config.toml"
                - name: RUST_LOG
                  value: "info"
          volumes:
            - name: climbsheet-volume
              persistentVolumeClaim:
                claimName: climbsheet-pvc

