{{- $fullName := printf "%s-%s" (include "climbsheet.fullname" .) "pv" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
   storage: 1000Gi
  claimRef:
    namespace: default
    name: climbsheet-pvc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/volume-fsn1-1/local-storage/climbsheet"
