#!/usr/bin/env bash

set -euo pipefail

git_root="$(git rev-parse --show-toplevel)"
image="climbsheet"
commit=$(git rev-parse --verify HEAD)

cd "$(git rev-parse --show-toplevel)"

docker build -t $image .
docker tag $image "$REGISTRY/$image:$commit"
docker tag $image "$REGISTRY/$image:latest"
docker push --all-tags "$REGISTRY/$image"
docker push "$REGISTRY/$image"

image_with_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $image:latest)"

helm upgrade \
	--reuse-values \
	--set image="$image_with_sha" \
	"$HELM_RELEASE" "$git_root/deploy/chart"
